import type { Metadata } from "next";
import { Rubik_Glitch, Share_Tech_Mono } from "next/font/google";
import "@/styles/main.css";
import { AppProvider } from "@/contexts/AppContext";

const rubikGlitch = Rubik_Glitch({
  variable: "--font-rubik-glitch",
  subsets: ["latin"],
  weight: ["400"],
});

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikGlitch.variable} ${shareTechMono.variable}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
