import type { Metadata } from "next";
import { Rubik_Glitch } from "next/font/google";
import "./globals.css";

const rubikGlitch = Rubik_Glitch({
  variable: "--font-rubik-glitch",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikGlitch.variable}`}>{children}</body>
    </html>
  );
}
